apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-prd
  namespace: prd
data:
  index.html: |
    <html>
      <body>
        <h1>This is PRD</h1>
        <p>Welcome to nginx!</p>
      </body>
    </html>