apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-dev
  namespace: dev
data:
  index.html: |
    <html>
      <body>
        <h1>This is DEV</h1>
        <p>Welcome to nginx!</p>
      </body>
    </html>